リノート時にアイコンの右下にインスタンスの画像を設置した
Kinoshita0623/MisskeyAndroidClient pull request #1882
Opened 2023-09-19 14:23 UTC by sanao1006

## やったこと
- リノート時にアイコンの右下にインスタンスの画像を設置した
- `AccountViewModel`を使わないように修正した
  - https://github.com/pantasystem/Milktea/pull/1880#issuecomment-1725548008

## Issue番号
Close #1447

2023-09-19 14:28 UTC, sanao1006 commented
なんかいろいろわちゃわちゃしたので新しくPR作り直しました。ご迷惑をおかけしました🙇‍♀️

2023-09-19 14:48 UTC, pantasystem requested changes
コメントしました。

2023-09-19 14:48 UTC, pantasystem commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteTargetAccountList.kt
> +    accountIdToIconUrlMap: Map<Long, String>,
AccountInfoがinstanceIconUrlを保持していると思うのですが、Map形に変換した理由とかあるのでしょうか？
特に理由などがない場合はMap形に変換せずそのまま、AccountInfoのinstanceIconUrlを使えそうだと思いました。

2023-09-19 14:48 UTC, pantasystem commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteBottomSheetDialog.kt
> +                    val accountIdToIconUrlMap = uiState.accounts.map {
別のコメントで指摘しましたが、これも同様です。あとはこの書き方だとRecomposeされるたびにMapに変換される処理が実行されるので、rememberなどを使って計算結果をキャッシュするようにしたいです。

2023-09-19 14:59 UTC, sanao1006 commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteTargetAccountList.kt
> +    accountIdToIconUrlMap: Map<Long, String>,
AccountInfoにinstanceIconUrlがなかった時の実装に引っ張られてました。たしかにAccountInfoがinstanceIconUrlをもっているのでaccountIdToIconUrlMapはもう不必要ですね。

2023-09-19 15:23 UTC, sanao1006 commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteBottomSheetDialog.kt
> +                    val accountIdToIconUrlMap = uiState.accounts.map {
accountIdToIconUrlMapは削除するとして
> rememberなどを使って計算結果をキャッシュするようにしたいです。

ちょっと考えてもよくわからなかったのでもしrememberつかうならどんな感じになるか教えてくれるとありがたいです！！

2023-09-19 15:38 UTC, pantasystem commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteBottomSheetDialog.kt
> +                    val accountIdToIconUrlMap = uiState.accounts.map {
こういうことですね
rememberはkeyとなる値と、実際に処理を実行する関数を受け取る仕組みになっていて、
keyの値が更新されると関数が評価される仕組みになっています。
```Kotlin
                    val accountIdToIconUrlMap = remember(uiState.accounts) {
                        uiState.accounts.map {
                            it.accountId to (it.instanceIconUrl ?: "")
                        }.toMap()
                    }
```

2023-09-19 15:40 UTC, sanao1006 commented on modules/features/note/src/main/java/net/pantasystem/milktea/note/renote/RenoteBottomSheetDialog.kt
> +                    val accountIdToIconUrlMap = uiState.accounts.map {
これは本当に知見でした。ありがとうございます！！

2023-09-20 01:40 UTC, pantasystem approved these changes
![LGTM](https://image.lgtmoon.dev/222728)

2023-09-20 01:47 UTC, merged