feat: フォローボタンのデザインをわかりやすくする
Kinoshita0623/MisskeyAndroidClient pull request #1961
Opened 2023-11-12 13:00 UTC by sanao1006

# 概要
以前までは、プロフィール画面、ユーザ一覧画面のフォローボタンのデザインがフォロー・非フォロー状態に関わらず同じような見た目で分かりづらかった。 

# 変更点
- プロフィール画面のフォローボタンのデザインを、ユーザー一覧画面のようにフォロー・非フォロー状態次第で見た目を切り替える

## スクリーンショット(任意)
フォロー中 | 非フォロー |  非フォロー申請済み | 非フォロー未申請 |
:--: | :--:| :--:| :--:
![image](https://github.com/pantasystem/Milktea/assets/62137820/15950ce3-01cb-4758-81a3-dcc5fc56fa62)|![image](https://github.com/pantasystem/Milktea/assets/62137820/8875ce9f-ecd0-4665-a8c4-faa01a0268e9)|![image](https://github.com/pantasystem/Milktea/assets/62137820/7c10743d-e544-4b20-817a-9d9bc9a6f88a)|![image](https://github.com/pantasystem/Milktea/assets/62137820/ea36022d-dd28-4d62-939a-612f9ceaa025)|

## Issue番号
Fixes #1955

2023-11-12 13:32 UTC, sanao1006 commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    private fun setFollowState(state: FollowState?): String = when (state) {
["followState"BindingAdapter](https://github.com/pantasystem/Milktea/blob/c934497ab4f34a12be23cbb097c02ef3be94c9ae/modules/features/user/src/main/java/net/pantasystem/milktea/user/helper/FollowStateHelper.kt#L12)をいい感じに変形したりして再利用したかったが、Jetpack ComposeとBindingAdapterの合わせ方がよくわからなかったためこの関数を作成した

2023-11-12 13:49 UTC, pantasystem reviewed
ご確認よろしくお願いします🙇

2023-11-12 13:49 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +            }
Composable関数に切り出すて実装するとよりよく実装できるのではないかと思いました。

2023-11-12 13:49 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    private fun setFollowState(state: FollowState?): String = when (state) {
https://github.com/pantasystem/Milktea/pull/1961/files#diff-c2246cd8b802c5448fccf91488f790ff9f7d8884b207d7773a68d7eaf24f951dR203-R221 をComposable関数で切り出した上で、[stringResource](https://developer.android.com/jetpack/compose/resources?hl=ja)関数で取得するのが良いと思いました。

2023-11-12 14:22 UTC, sanao1006 commented
修正しました！
確認よろしくおねがいします！

2023-11-12 14:57 UTC, sanao1006 commented
メモリエラーですか🤔

onCreateの中にComposable関数を書いたのがよくなかったかもしれない...？

2023-11-13 12:22 UTC, pantasystem reviewed
ご確認お願いします。

2023-11-13 12:22 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +                        buttonText = buttonText,
buttonTextの取得処理はFollowButtonの中に閉じてしまうのが好ましいと思いました。
理由としてはFollowButton自体が状態を受け取り、
それに応じて表示内容を切り替えているので、FollowButtonの中に閉じてしまうのが良いと思いました。

2023-11-13 12:22 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +        buttonText: String,
userDetailは直値指定で、isMineがState経由なのが気になりました。
何かわけがあるのでしょうか？

2023-11-13 12:22 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +                else -> {  }
elseを使用してしまうと、将来的にFollowStateに状態が追加された時に、
その変更を見落としてしまうことに繋がりかねないので、
null -> {} にしたほうが良いと思いました。

2023-11-13 12:22 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +                        onClick = { mViewModel.changeFollow() },
直接ViewModelを制御してしまうとComposable関数としての再利用性、テスト容易性が低下してしまうので、
一度コールバックとしてイベントを戻してあげて、そこでViewModelにイベントを伝えてあげるのが良いと思いました。
また別ファイルとしてComposable関数として切り出すことによって、
フォロー一覧画面などで使われている、[UserDetailCard](https://github.com/pantasystem/Milktea/blob/c934497ab4f34a12be23cbb097c02ef3be94c9ae/modules/features/user/src/main/java/net/pantasystem/milktea/user/compose/UserDetailCard.kt#L40-L40)でも再使用できるようになりそうだと思いました。

2023-11-13 12:34 UTC, sanao1006 commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +        buttonText: String,
すみません、これはおそらく
```kotlin
val isMine = mViewModel.isMine.collectAsState()
```
のところで、`by`を間違えて`=`にしていたからですね。
普通にミスっていました🙇

2023-11-13 13:03 UTC, sanao1006 commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +                        onClick = { mViewModel.changeFollow() },
思ったんですけど、[serStateActionButton](https://github.com/pantasystem/Milktea/blob/c934497ab4f34a12be23cbb097c02ef3be94c9ae/modules/features/user/src/main/java/net/pantasystem/milktea/user/compose/UserDetailCard.kt#L219)にならってFollowButtonには`FollowState?`を直接渡すのってどうですかね？

userDetailはfollowStateしか使ってないのでこの方が軽くなるかなと思ったからです

2023-11-14 06:09 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +                        onClick = { mViewModel.changeFollow() },
そのほうがPreviewを表示する時に渡す引数を少なくできて良さそうだと思いました

2023-11-14 12:23 UTC, sanao1006 commented
@pantasystem 

お手すきの際にご確認お願いします🙇

2023-11-15 03:37 UTC, pantasystem requested changes
お手隙の際にご確認よろしくお願いします。

2023-11-15 03:37 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    fun FollowButton(
別ファイルに切り出したほうが視認性が良くなると思いました。
当初は文字列リソースを得るためにcontextへの参照が必要なため
Activity中に実装していたと思うのですが、
stringResourceは直接的なContextへの参照は不要なため、別ファイルに切り出せると思います。

2023-11-15 03:37 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    private fun setFollowState(state: FollowState?): String = when (state) {
実際には値をsetしていないので、getXXXなどにリネームしていただきたいです。

2023-11-15 12:46 UTC, sanao1006 commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    fun FollowButton(
FollowButtonを切り出したファイルの置き場所ですが、`modules/features/user/.../user/compose`の中で問題ないでしょうか？
それとも`modules/features/user/.../user`直下あたりでしょうか。微妙に迷っています。。。

2023-11-15 13:22 UTC, pantasystem commented on modules/features/user/src/main/java/net/pantasystem/milktea/user/profile/UserDetailActivity.kt
> +    fun FollowButton(
今回はこの機能（画面）で使われることを前提としているので、`modules/features/user/.../user` で良いかと思われます。

2023-11-16 09:36 UTC, pantasystem approved these changes
お疲れ様でした！
コントリビュートありがとうございました🙇
![LGTM](https://image.lgtmoon.dev/72640)

2023-11-16 09:36 UTC, merged

2023-11-16 09:43 UTC, sanao1006 commented
こちらこそ丁寧にレビューありがとうございました‼️